#!/bin/bash
# Compresses nets/ into data/*.tar.gz.part### chunks (<=10MB each) + checksums,
# for a release target with a per-file size limit (GitHub). Run from the repo root
# once nets/ holds the data (regenerated by scripts/, or unpacked by reassemble.sh).
#
# Meant to run as a SLURM job (see submit_package_data.sh): tar/gzip over
# thousands of small files is slow on a networked filesystem and should not run on
# a login node.
#
# Usage:
#   bash package_data.sh                      # every archive
#   bash package_data.sh LFC_240_ws_gt        # just these, leaving the rest
#
# Naming one or more archives repackages only those: their old chunks are
# replaced and both checksum files are rebuilt to cover everything then present
# in data/, so a partial run leaves the directory self-consistent.
#
# Optional env vars:
#   NETS_ROOT   directory holding LFC/ and spec_div/   (default: nets)
#   DATA_DIR    directory to write the chunks into      (default: data)
#   MAX_TOTAL_MB  abort if data/ chunks exceed this     (default: 1000, GitHub's
#                 recommended repository size)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

NETS_ROOT="${NETS_ROOT:-nets}"
DATA_DIR="${DATA_DIR:-data}"
MAX_TOTAL_MB="${MAX_TOTAL_MB:-1000}"
CHUNK_BYTES=$((10 * 1024 * 1024))

# Editor/rerun leftovers and lock files are excluded rather than deleted, so
# packaging never mutates nets/. '*_eig_cache.npz' is a derived cache that
# lfc_data_loader.pooled_eig_laplacians() would read instead of the .gt files;
# it is rebuilt on demand and must not ship.
TAR_EXCLUDES=(
  --exclude='*.bak'
  --exclude='*~'
  --exclude='*.tmp'
  --exclude='*.lock'
  --exclude='__pycache__'
  --exclude='.ipynb_checkpoints'
  --exclude='*_eig_cache.npz'
)

# Archive name -> members, as shell globs relative to NETS_ROOT. Graph (.gt) files
# and tables (CSV) are kept in separate archives.
archive_members() {
  case "$1" in
    LFC_240_ws_gt)            echo "LFC/240/ws/16_seed1 LFC/240/ws/16_seed2" ;;
    LFC_240_mhk_gt)           echo "LFC/240/mhk/16_seed1" ;;
    spec_div_top_pairs_gt)    echo "spec_div/ws_seed_5/pair_263_G1.gt spec_div/ws_seed_5/pair_263_G2.gt spec_div/mhk_seed_8/pair_376_G1.gt spec_div/mhk_seed_8/pair_376_G2.gt" ;;
    LFC_240_ws_csv)           echo "LFC/240/ws/*.csv" ;;
    LFC_240_mhk_csv)          echo "LFC/240/mhk/*.csv" ;;
    spec_div_ws_csv)          echo "spec_div/all_graph_eigenvalues_ws.csv spec_div/all_graph_eigenvalues_norm_ws.csv spec_div/all_graphs_h2_data_ws.csv spec_div/ws_seed_*/pairs_index.csv" ;;
    spec_div_mhk_csv)         echo "spec_div/all_graph_eigenvalues_mhk.csv spec_div/all_graph_eigenvalues_norm_mhk.csv spec_div/all_graphs_h2_data_mhk.csv spec_div/mhk_seed_*/pairs_index.csv" ;;
    spec_div_pair_properties) echo "spec_div/pair_properties" ;;
    *) return 1 ;;
  esac
}

ARCHIVES=(
  LFC_240_ws_gt LFC_240_mhk_gt spec_div_top_pairs_gt
  LFC_240_ws_csv LFC_240_mhk_csv
  spec_div_ws_csv spec_div_mhk_csv spec_div_pair_properties
)

if [[ $# -eq 0 ]]; then
  SELECTED=("${ARCHIVES[@]}")
else
  SELECTED=("$@")
  for want in "${SELECTED[@]}"; do
    if ! archive_members "$want" > /dev/null; then
      echo "Unknown archive '${want}'. Known: ${ARCHIVES[*]}" >&2
      exit 1
    fi
  done
fi

mkdir -p "$DATA_DIR"
touch "$DATA_DIR/checksums_full.sha256"

for name in "${SELECTED[@]}"; do
  # Expand the member globs inside NETS_ROOT and fail loudly on any that match nothing.
  members=()
  for pattern in $(archive_members "$name"); do
    matches=( $(cd "$NETS_ROOT" && compgen -G "$pattern" || true) )
    if [[ ${#matches[@]} -eq 0 ]]; then
      echo "Missing ${NETS_ROOT}/${pattern} - nothing to package for ${name}" >&2
      exit 1
    fi
    members+=("${matches[@]}")
  done

  # Drop chunks from a previous run of THIS archive, so a shrinking dataset
  # cannot leave orphaned high-numbered parts behind.
  rm -f "${DATA_DIR}/${name}".tar.gz.part*

  echo "Packaging ${name}: ${#members[@]} member path(s)"
  tar -czf "${DATA_DIR}/${name}.tar.gz" "${TAR_EXCLUDES[@]}" -C "$NETS_ROOT" "${members[@]}"

  echo "Splitting ${DATA_DIR}/${name}.tar.gz into <=10MB parts"
  split -b "$CHUNK_BYTES" -d -a 3 "${DATA_DIR}/${name}.tar.gz" "${DATA_DIR}/${name}.tar.gz.part"

  # Recorded as 'data/<name>.tar.gz' regardless of DATA_DIR: that is the path
  # reassemble.sh reconstructs and checks on the downloading side.
  new_sum="$(sha256sum "${DATA_DIR}/${name}.tar.gz" | cut -d' ' -f1)"
  rm "${DATA_DIR}/${name}.tar.gz"
  grep -v "  data/${name}\.tar\.gz\$" "$DATA_DIR/checksums_full.sha256" \
      > "$DATA_DIR/checksums_full.sha256.tmp" || true
  echo "${new_sum}  data/${name}.tar.gz" >> "$DATA_DIR/checksums_full.sha256.tmp"
  mv "$DATA_DIR/checksums_full.sha256.tmp" "$DATA_DIR/checksums_full.sha256"
done

# Rewrite checksums_full in canonical ARCHIVES order.
: > "$DATA_DIR/checksums_full.sha256.tmp"
for name in "${ARCHIVES[@]}"; do
  grep "  data/${name}\.tar\.gz\$" "$DATA_DIR/checksums_full.sha256" \
      >> "$DATA_DIR/checksums_full.sha256.tmp" || true
done
mv "$DATA_DIR/checksums_full.sha256.tmp" "$DATA_DIR/checksums_full.sha256"

echo "Computing checksums of chunks"
(cd "$DATA_DIR" && sha256sum *.tar.gz.part* > checksums_parts.sha256)

# Pushability gate: every chunk within the split size, total within MAX_TOTAL_MB.
largest=$(find "$DATA_DIR" -name '*.tar.gz.part*' -printf '%s\n' | sort -n | tail -1)
total=$(find "$DATA_DIR" -name '*.tar.gz.part*' -printf '%s\n' | awk '{s+=$1} END {print s+0}')
if (( largest > CHUNK_BYTES )); then
  echo "ERROR: a chunk is ${largest} bytes, above ${CHUNK_BYTES}" >&2
  exit 1
fi
if (( total > MAX_TOTAL_MB * 1000 * 1000 )); then
  echo "ERROR: data/ chunks total ${total} bytes, above ${MAX_TOTAL_MB} MB" >&2
  exit 1
fi

echo
echo "Done. Packaged: ${SELECTED[*]}"
echo "Chunks in ${DATA_DIR}: $(ls "$DATA_DIR"/*.tar.gz.part* | wc -l), total $((total / 1000000)) MB, largest $((largest / 1000000)) MB"
echo
cat "$DATA_DIR/checksums_full.sha256"
